GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

DELETE  http://localhost:8000/products/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMjg3MzUzLCJpYXQiOjE3NjEyODcwNTMsImp0aSI6ImQzZWNkZTk2YTgwNTRhMjE4YTU5NWI4NGNjOGY1YmNjIiwidXNlcl9pZCI6IjEifQ.c_dS8E-V95VS2cCYdd4WKmD_Tg5qCUMKjJrWAEHZLZg

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMjg3MzUzLCJpYXQiOjE3NjEyODcwNTMsImp0aSI6ImQzZWNkZTk2YTgwNTRhMjE4YTU5NWI4NGNjOGY1YmNjIiwidXNlcl9pZCI6IjEifQ.c_dS8E-V95VS2cCYdd4WKmD_Tg5qCUMKjJrWAEHZLZg

{
  "name": "Television",
  "price": 19.99,
  "description": "A description of the other new product.",
  "stock": 100
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMzIyNzk0LCJpYXQiOjE3NjEzMjI0OTQsImp0aSI6IjdhYjFhZDBhYjU4MDQ5OWY4MjQ1Mjg3MmYyZDg5MTQzIiwidXNlcl9pZCI6IjEifQ.oSzbl4uG2oTxEX5ayAdxslJykD-vrT8dxT0p0TA1OeI

{
  "name": "refreshing Token Authenticated Product",
  "price": 19.99,
  "description": "A description of the other new product.",
  "stock": 100
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "john-doe",
  "password": "john"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MTgwMjM3NiwiaWF0IjoxNzYxNzE1OTc2LCJqdGkiOiI4YTAwYjMyY2U4ODY0Njg3ODQzMGNlMjdjY2ZmZWNlMyIsInVzZXJfaWQiOiIyIn0.LsvwpZInTIjr6KgM9rl5ylFaIAn3BZ2d0OwqcZkDTow"
}

###

GET http://localhost:8000/orders/?created_at=2025-10-17 HTTP/1.1

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNzE3NjQzLCJpYXQiOjE3NjE3MTczNDQsImp0aSI6IjhkNzg5MGQ3NTIwYzRiOWI4YzVjNjcxOTY4YjBlM2E0IiwidXNlcl9pZCI6IjIifQ.IoISzcjjqtGumreWWc78CUsNAHepqaaZqNJRsKSJruI


###

POST  http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNzE3OTk1LCJpYXQiOjE3NjE3MTc2OTUsImp0aSI6IjI4MTkxZGZlYTA3MTQxNmRhNDc5OWVmMTRiMWI3MTkwIiwidXNlcl9pZCI6IjIifQ.Mn8QvDlaIO-QQ98faxKkn9uQYLgckNrdogBzVdVjiHk

{
  "status": "Pending",
  "user": 2,
  "items": [
    {
      "product": 3,
      "quantity": 2
    },
    {
      "product": 5,
      "quantity": 1
    }
  ]
}