# @name login
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "john-doe",
  "password": "john"
}

###

@refresh = {{login.response.body.refresh}}

# @name access_token
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "{{refresh}}"
}

###

@access = {{access_token.response.body.access}}

GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/7/ HTTP/1.1

###

DELETE  http://localhost:8000/products/2/ HTTP/1.1
Authorization: Bearer {{access}}

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}

{
  "name": "Television",
  "price": 19.99,
  "description": "A description of the other new product.",
  "stock": 100
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}

{
  "name": "refreshing Token Authenticated Product",
  "price": 19.99,
  "description": "A description of the other new product.",
  "stock": 100
}

###

GET http://localhost:8000/orders/?created_at=2025-10-17 HTTP/1.1

###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer {{access}}


###

POST  http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access}}

{
  "status": "Confirmed",
  "items": [
    {
      "product": 5,
      "quantity": 20
    },
    {
      "product": 5,
      "quantity": 10
    }
  ]
}

###

DELETE  http://localhost:8000/orders/4a7593f4-043d-45ff-9b12-32279d5a16c6/ HTTP/1.1
Authorization: Bearer {{access}}